// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kobe.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Playbooks            []string `protobuf:"bytes,2,rep,name=playbooks,proto3" json:"playbooks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetPlaybooks() []string {
	if m != nil {
		return m.Playbooks
	}
	return nil
}

type Host struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int32             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	User                 string            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password             string            `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,6,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{1}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Host) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Host) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Host) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Group struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hosts                []string          `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Children             []string          `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,4,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{2}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Group) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Group) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Inventory struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Groups               []*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{3}
}

func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (m *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(m, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Inventory) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{4}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type CreateProjectResponse struct {
	Item                 *Project `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{5}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetItem() *Project {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListProjectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectRequest) Reset()         { *m = ListProjectRequest{} }
func (m *ListProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectRequest) ProtoMessage()    {}
func (*ListProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{6}
}

func (m *ListProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectRequest.Unmarshal(m, b)
}
func (m *ListProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectRequest.Merge(m, src)
}
func (m *ListProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectRequest.Size(m)
}
func (m *ListProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectRequest proto.InternalMessageInfo

type ListProjectResponse struct {
	Items                []*Project `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectResponse) Reset()         { *m = ListProjectResponse{} }
func (m *ListProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectResponse) ProtoMessage()    {}
func (*ListProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{7}
}

func (m *ListProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectResponse.Unmarshal(m, b)
}
func (m *ListProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectResponse.Merge(m, src)
}
func (m *ListProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectResponse.Size(m)
}
func (m *ListProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectResponse proto.InternalMessageInfo

func (m *ListProjectResponse) GetItems() []*Project {
	if m != nil {
		return m.Items
	}
	return nil
}

type RunPlaybookRequest struct {
	Project              string     `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Playbook             string     `protobuf:"bytes,2,opt,name=playbook,proto3" json:"playbook,omitempty"`
	Inventory            *Inventory `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunPlaybookRequest) Reset()         { *m = RunPlaybookRequest{} }
func (m *RunPlaybookRequest) String() string { return proto.CompactTextString(m) }
func (*RunPlaybookRequest) ProtoMessage()    {}
func (*RunPlaybookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{8}
}

func (m *RunPlaybookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlaybookRequest.Unmarshal(m, b)
}
func (m *RunPlaybookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlaybookRequest.Marshal(b, m, deterministic)
}
func (m *RunPlaybookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlaybookRequest.Merge(m, src)
}
func (m *RunPlaybookRequest) XXX_Size() int {
	return xxx_messageInfo_RunPlaybookRequest.Size(m)
}
func (m *RunPlaybookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlaybookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlaybookRequest proto.InternalMessageInfo

func (m *RunPlaybookRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RunPlaybookRequest) GetPlaybook() string {
	if m != nil {
		return m.Playbook
	}
	return ""
}

func (m *RunPlaybookRequest) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type Result struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Finished             bool     `protobuf:"varint,5,opt,name=finished,proto3" json:"finished,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{9}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Result) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Result) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WatchStream struct {
	Stream               []byte   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Result               *Result  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchStream) Reset()         { *m = WatchStream{} }
func (m *WatchStream) String() string { return proto.CompactTextString(m) }
func (*WatchStream) ProtoMessage()    {}
func (*WatchStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{10}
}

func (m *WatchStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchStream.Unmarshal(m, b)
}
func (m *WatchStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchStream.Marshal(b, m, deterministic)
}
func (m *WatchStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchStream.Merge(m, src)
}
func (m *WatchStream) XXX_Size() int {
	return xxx_messageInfo_WatchStream.Size(m)
}
func (m *WatchStream) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchStream.DiscardUnknown(m)
}

var xxx_messageInfo_WatchStream proto.InternalMessageInfo

func (m *WatchStream) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *WatchStream) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetInventoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInventoryRequest) Reset()         { *m = GetInventoryRequest{} }
func (m *GetInventoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetInventoryRequest) ProtoMessage()    {}
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{11}
}

func (m *GetInventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInventoryRequest.Unmarshal(m, b)
}
func (m *GetInventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInventoryRequest.Marshal(b, m, deterministic)
}
func (m *GetInventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventoryRequest.Merge(m, src)
}
func (m *GetInventoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetInventoryRequest.Size(m)
}
func (m *GetInventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventoryRequest proto.InternalMessageInfo

func (m *GetInventoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetInventoryResponse struct {
	Item                 *Inventory `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetInventoryResponse) Reset()         { *m = GetInventoryResponse{} }
func (m *GetInventoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetInventoryResponse) ProtoMessage()    {}
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{12}
}

func (m *GetInventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInventoryResponse.Unmarshal(m, b)
}
func (m *GetInventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInventoryResponse.Marshal(b, m, deterministic)
}
func (m *GetInventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventoryResponse.Merge(m, src)
}
func (m *GetInventoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetInventoryResponse.Size(m)
}
func (m *GetInventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventoryResponse proto.InternalMessageInfo

func (m *GetInventoryResponse) GetItem() *Inventory {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "api.Project")
	proto.RegisterType((*Host)(nil), "api.Host")
	proto.RegisterMapType((map[string]string)(nil), "api.Host.VarsEntry")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterMapType((map[string]string)(nil), "api.Group.VarsEntry")
	proto.RegisterType((*Inventory)(nil), "api.Inventory")
	proto.RegisterType((*CreateProjectRequest)(nil), "api.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "api.CreateProjectResponse")
	proto.RegisterType((*ListProjectRequest)(nil), "api.ListProjectRequest")
	proto.RegisterType((*ListProjectResponse)(nil), "api.ListProjectResponse")
	proto.RegisterType((*RunPlaybookRequest)(nil), "api.RunPlaybookRequest")
	proto.RegisterType((*Result)(nil), "api.Result")
	proto.RegisterType((*WatchStream)(nil), "api.WatchStream")
	proto.RegisterType((*GetInventoryRequest)(nil), "api.GetInventoryRequest")
	proto.RegisterType((*GetInventoryResponse)(nil), "api.GetInventoryResponse")
}

func init() { proto.RegisterFile("kobe.proto", fileDescriptor_77244b2e22c40370) }

var fileDescriptor_77244b2e22c40370 = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xae, 0xf3, 0xc7, 0xad, 0xc7, 0xfd, 0x55, 0xd5, 0x36, 0x3f, 0x70, 0x2d, 0x24, 0xa2, 0x45,
	0x88, 0x1c, 0x50, 0x84, 0xc2, 0x01, 0x5a, 0xb8, 0x50, 0x54, 0xb5, 0xfc, 0x39, 0x54, 0x0b, 0x82,
	0xb3, 0xe3, 0x2c, 0x8d, 0x69, 0xe2, 0x35, 0xbb, 0xeb, 0x42, 0xde, 0x85, 0x27, 0xe0, 0xc4, 0xa3,
	0xf0, 0x48, 0x68, 0xc7, 0xbb, 0x9b, 0xa4, 0xcd, 0x91, 0xdb, 0x7e, 0xf3, 0xcd, 0xce, 0x7c, 0x33,
	0xfb, 0xd9, 0x00, 0x57, 0x62, 0xcc, 0x87, 0x95, 0x14, 0x5a, 0x90, 0x76, 0x56, 0x15, 0xf4, 0x05,
	0x6c, 0x5f, 0x48, 0xf1, 0x95, 0xe7, 0x9a, 0x10, 0xe8, 0x94, 0xd9, 0x9c, 0x27, 0x41, 0x3f, 0x18,
	0x44, 0x0c, 0xcf, 0xe4, 0x1e, 0x44, 0xd5, 0x2c, 0x5b, 0x8c, 0x85, 0xb8, 0x52, 0x49, 0xab, 0xdf,
	0x1e, 0x44, 0x6c, 0x19, 0xa0, 0x7f, 0x02, 0xe8, 0x9c, 0x0b, 0xa5, 0xc9, 0x1e, 0xb4, 0x8a, 0xca,
	0x5e, 0x6c, 0x15, 0x95, 0x2f, 0xd5, 0x5a, 0x29, 0x45, 0xa0, 0x53, 0x09, 0xa9, 0x93, 0x76, 0x3f,
	0x18, 0x74, 0x19, 0x9e, 0x4d, 0xac, 0x56, 0x5c, 0x26, 0x9d, 0x26, 0xcf, 0x9c, 0x49, 0x0a, 0x3b,
	0x55, 0xa6, 0xd4, 0x77, 0x21, 0x27, 0x49, 0x17, 0xe3, 0x1e, 0x93, 0x47, 0xd0, 0xb9, 0xce, 0xa4,
	0x4a, 0xc2, 0x7e, 0x7b, 0x10, 0x8f, 0x0e, 0x86, 0x59, 0x55, 0x0c, 0x8d, 0x80, 0xe1, 0xa7, 0x4c,
	0xaa, 0xd3, 0x52, 0xcb, 0x05, 0xc3, 0x84, 0xf4, 0x19, 0x44, 0x3e, 0x44, 0xf6, 0xa1, 0x7d, 0xc5,
	0x17, 0x56, 0x9e, 0x39, 0x92, 0x1e, 0x74, 0xaf, 0xb3, 0x59, 0xed, 0x04, 0x36, 0xe0, 0xb8, 0xf5,
	0x3c, 0xa0, 0xbf, 0x03, 0xe8, 0x9e, 0x49, 0x51, 0x57, 0x1b, 0xd7, 0xd1, 0x83, 0xee, 0x54, 0x28,
	0xed, 0x56, 0xd1, 0x00, 0xa3, 0x38, 0x9f, 0x16, 0xb3, 0x89, 0xe4, 0x65, 0xd2, 0x46, 0xc2, 0x63,
	0x32, 0xb0, 0x8a, 0x3b, 0xa8, 0xb8, 0x87, 0x8a, 0xb1, 0xfe, 0xbf, 0x93, 0x7c, 0x01, 0xd1, 0x9b,
	0xf2, 0x9a, 0x97, 0x5a, 0xc8, 0x05, 0xb9, 0xef, 0x14, 0x06, 0xd8, 0x30, 0xf2, 0x2b, 0x72, 0x62,
	0x29, 0x84, 0x97, 0xa6, 0x7f, 0x33, 0x43, 0x3c, 0x82, 0xa5, 0x24, 0x66, 0x19, 0x7a, 0x02, 0xbd,
	0xd7, 0x92, 0x67, 0x9a, 0x5b, 0x6b, 0x30, 0xfe, 0xad, 0xe6, 0x6a, 0xb3, 0x43, 0xee, 0x40, 0xa8,
	0x44, 0x2d, 0x73, 0x27, 0xcc, 0x22, 0x7a, 0x04, 0xff, 0xdf, 0xa8, 0xa1, 0x2a, 0x51, 0x2a, 0x4e,
	0xfa, 0xd0, 0x29, 0x34, 0x9f, 0x63, 0x91, 0x78, 0xb4, 0x8b, 0xed, 0x5d, 0x0e, 0x32, 0xb4, 0x07,
	0xe4, 0x7d, 0xa1, 0xf4, 0x7a, 0x73, 0x7a, 0x04, 0x07, 0x6b, 0x51, 0x5b, 0x8e, 0x42, 0xd7, 0x5c,
	0x72, 0x03, 0xaf, 0xd7, 0x6b, 0x28, 0xfa, 0x03, 0x08, 0xab, 0xcb, 0x0b, 0xeb, 0x5b, 0x37, 0x4d,
	0x02, 0xdb, 0x55, 0x93, 0x67, 0x07, 0x72, 0x10, 0x2d, 0x68, 0x93, 0xed, 0x54, 0x1e, 0x93, 0xc7,
	0x10, 0x15, 0x6e, 0xdb, 0xe8, 0xe5, 0x78, 0xb4, 0x87, 0x3d, 0xfd, 0x1b, 0xb0, 0x65, 0x02, 0xfd,
	0x15, 0x40, 0xc8, 0xb8, 0xaa, 0x67, 0xda, 0x7c, 0x4a, 0x4a, 0x67, 0x52, 0x7f, 0x2c, 0xfc, 0x06,
	0x97, 0x01, 0x23, 0x86, 0x97, 0x13, 0xe4, 0x9a, 0x8e, 0x0e, 0x1a, 0x66, 0xce, 0x95, 0xca, 0x2e,
	0x39, 0xb6, 0x8b, 0x98, 0x83, 0x86, 0x51, 0x75, 0x9e, 0x73, 0xa5, 0xf0, 0x03, 0xda, 0x61, 0x0e,
	0x9a, 0x01, 0xbe, 0x14, 0x65, 0xa1, 0xa6, 0xbc, 0xf9, 0x86, 0x76, 0x98, 0xc7, 0xe6, 0x56, 0x2e,
	0x4a, 0xcd, 0x4b, 0x9d, 0x84, 0x4d, 0x3d, 0x0b, 0xe9, 0x5b, 0x88, 0x3f, 0x67, 0x3a, 0x9f, 0x7e,
	0xd0, 0x92, 0x67, 0x73, 0x7c, 0x59, 0x3c, 0xa1, 0xda, 0x5d, 0x66, 0x11, 0x79, 0x00, 0xa1, 0xc4,
	0x91, 0x50, 0x69, 0x3c, 0x8a, 0x71, 0xfc, 0x66, 0x4a, 0x66, 0x29, 0xfa, 0x10, 0x0e, 0xce, 0xb8,
	0x5e, 0xee, 0xc4, 0xee, 0xdc, 0xfc, 0x28, 0x26, 0xfe, 0x47, 0x31, 0xa1, 0xc7, 0xd0, 0x5b, 0x4f,
	0xf3, 0xaf, 0xba, 0x6a, 0x92, 0x9b, 0x0b, 0x46, 0x6e, 0xf4, 0xb3, 0x05, 0xdb, 0xef, 0xc4, 0x98,
	0xbf, 0xaa, 0x0a, 0x72, 0x0e, 0xff, 0xad, 0xb9, 0x8d, 0x1c, 0xe2, 0x95, 0x4d, 0x2e, 0x4e, 0xd3,
	0x4d, 0x54, 0xd3, 0x97, 0x6e, 0x91, 0x13, 0x88, 0x57, 0x6c, 0x46, 0xee, 0x62, 0xf2, 0x6d, 0x3b,
	0xa6, 0xc9, 0x6d, 0xc2, 0xd7, 0x38, 0x85, 0xdd, 0xd5, 0xa9, 0x48, 0x93, 0xbb, 0x61, 0x1f, 0xe9,
	0xe1, 0x06, 0xc6, 0x97, 0x79, 0x09, 0xf1, 0x8a, 0x6d, 0xad, 0x94, 0xdb, 0x46, 0x4e, 0xf7, 0x91,
	0x58, 0x79, 0x3a, 0xba, 0xf5, 0x24, 0x18, 0x87, 0xf8, 0x97, 0x7f, 0xfa, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xf7, 0x05, 0xc3, 0xf3, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KobeApiClient is the client API for KobeApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KobeApiClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	ListProject(ctx context.Context, in *ListProjectRequest, opts ...grpc.CallOption) (*ListProjectResponse, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	RunPlaybook(ctx context.Context, in *RunPlaybookRequest, opts ...grpc.CallOption) (KobeApi_RunPlaybookClient, error)
}

type kobeApiClient struct {
	cc *grpc.ClientConn
}

func NewKobeApiClient(cc *grpc.ClientConn) KobeApiClient {
	return &kobeApiClient{cc}
}

func (c *kobeApiClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) ListProject(ctx context.Context, in *ListProjectRequest, opts ...grpc.CallOption) (*ListProjectResponse, error) {
	out := new(ListProjectResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/ListProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/GetInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) RunPlaybook(ctx context.Context, in *RunPlaybookRequest, opts ...grpc.CallOption) (KobeApi_RunPlaybookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KobeApi_serviceDesc.Streams[0], "/api.KobeApi/RunPlaybook", opts...)
	if err != nil {
		return nil, err
	}
	x := &kobeApiRunPlaybookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KobeApi_RunPlaybookClient interface {
	Recv() (*WatchStream, error)
	grpc.ClientStream
}

type kobeApiRunPlaybookClient struct {
	grpc.ClientStream
}

func (x *kobeApiRunPlaybookClient) Recv() (*WatchStream, error) {
	m := new(WatchStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KobeApiServer is the server API for KobeApi service.
type KobeApiServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	ListProject(context.Context, *ListProjectRequest) (*ListProjectResponse, error)
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	RunPlaybook(*RunPlaybookRequest, KobeApi_RunPlaybookServer) error
}

// UnimplementedKobeApiServer can be embedded to have forward compatible implementations.
type UnimplementedKobeApiServer struct {
}

func (*UnimplementedKobeApiServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedKobeApiServer) ListProject(ctx context.Context, req *ListProjectRequest) (*ListProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProject not implemented")
}
func (*UnimplementedKobeApiServer) GetInventory(ctx context.Context, req *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (*UnimplementedKobeApiServer) RunPlaybook(req *RunPlaybookRequest, srv KobeApi_RunPlaybookServer) error {
	return status.Errorf(codes.Unimplemented, "method RunPlaybook not implemented")
}

func RegisterKobeApiServer(s *grpc.Server, srv KobeApiServer) {
	s.RegisterService(&_KobeApi_serviceDesc, srv)
}

func _KobeApi_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_ListProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).ListProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/ListProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).ListProject(ctx, req.(*ListProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/GetInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_RunPlaybook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunPlaybookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KobeApiServer).RunPlaybook(m, &kobeApiRunPlaybookServer{stream})
}

type KobeApi_RunPlaybookServer interface {
	Send(*WatchStream) error
	grpc.ServerStream
}

type kobeApiRunPlaybookServer struct {
	grpc.ServerStream
}

func (x *kobeApiRunPlaybookServer) Send(m *WatchStream) error {
	return x.ServerStream.SendMsg(m)
}

var _KobeApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.KobeApi",
	HandlerType: (*KobeApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _KobeApi_CreateProject_Handler,
		},
		{
			MethodName: "ListProject",
			Handler:    _KobeApi_ListProject_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _KobeApi_GetInventory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunPlaybook",
			Handler:       _KobeApi_RunPlaybook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kobe.proto",
}
