// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kobe.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Playbooks            []string `protobuf:"bytes,2,rep,name=playbooks,proto3" json:"playbooks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetPlaybooks() []string {
	if m != nil {
		return m.Playbooks
	}
	return nil
}

type Host struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int32             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	User                 string            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password             string            `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,6,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{1}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Host) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Host) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Host) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Group struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hosts                []string          `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Children             []string          `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,4,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{2}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Group) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Group) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Inventory struct {
	Hosts                []*Host  `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Groups               []*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{3}
}

func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (m *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(m, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Inventory) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{4}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type CreateProjectResponse struct {
	Item                 *Project `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{5}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetItem() *Project {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListProjectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectRequest) Reset()         { *m = ListProjectRequest{} }
func (m *ListProjectRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectRequest) ProtoMessage()    {}
func (*ListProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{6}
}

func (m *ListProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectRequest.Unmarshal(m, b)
}
func (m *ListProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectRequest.Merge(m, src)
}
func (m *ListProjectRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectRequest.Size(m)
}
func (m *ListProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectRequest proto.InternalMessageInfo

type ListProjectResponse struct {
	Items                []*Project `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectResponse) Reset()         { *m = ListProjectResponse{} }
func (m *ListProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectResponse) ProtoMessage()    {}
func (*ListProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{7}
}

func (m *ListProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectResponse.Unmarshal(m, b)
}
func (m *ListProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectResponse.Merge(m, src)
}
func (m *ListProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectResponse.Size(m)
}
func (m *ListProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectResponse proto.InternalMessageInfo

func (m *ListProjectResponse) GetItems() []*Project {
	if m != nil {
		return m.Items
	}
	return nil
}

type RunPlaybookRequest struct {
	Project              string     `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Playbook             string     `protobuf:"bytes,2,opt,name=playbook,proto3" json:"playbook,omitempty"`
	Inventory            *Inventory `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunPlaybookRequest) Reset()         { *m = RunPlaybookRequest{} }
func (m *RunPlaybookRequest) String() string { return proto.CompactTextString(m) }
func (*RunPlaybookRequest) ProtoMessage()    {}
func (*RunPlaybookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{8}
}

func (m *RunPlaybookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlaybookRequest.Unmarshal(m, b)
}
func (m *RunPlaybookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlaybookRequest.Marshal(b, m, deterministic)
}
func (m *RunPlaybookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlaybookRequest.Merge(m, src)
}
func (m *RunPlaybookRequest) XXX_Size() int {
	return xxx_messageInfo_RunPlaybookRequest.Size(m)
}
func (m *RunPlaybookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlaybookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlaybookRequest proto.InternalMessageInfo

func (m *RunPlaybookRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RunPlaybookRequest) GetPlaybook() string {
	if m != nil {
		return m.Playbook
	}
	return ""
}

func (m *RunPlaybookRequest) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type RunPlaybookResult struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPlaybookResult) Reset()         { *m = RunPlaybookResult{} }
func (m *RunPlaybookResult) String() string { return proto.CompactTextString(m) }
func (*RunPlaybookResult) ProtoMessage()    {}
func (*RunPlaybookResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{9}
}

func (m *RunPlaybookResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlaybookResult.Unmarshal(m, b)
}
func (m *RunPlaybookResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlaybookResult.Marshal(b, m, deterministic)
}
func (m *RunPlaybookResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlaybookResult.Merge(m, src)
}
func (m *RunPlaybookResult) XXX_Size() int {
	return xxx_messageInfo_RunPlaybookResult.Size(m)
}
func (m *RunPlaybookResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlaybookResult.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlaybookResult proto.InternalMessageInfo

func (m *RunPlaybookResult) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type RunAdhocRequest struct {
	Inventory            *Inventory `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Pattern              string     `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Module               string     `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Param                string     `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunAdhocRequest) Reset()         { *m = RunAdhocRequest{} }
func (m *RunAdhocRequest) String() string { return proto.CompactTextString(m) }
func (*RunAdhocRequest) ProtoMessage()    {}
func (*RunAdhocRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{10}
}

func (m *RunAdhocRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunAdhocRequest.Unmarshal(m, b)
}
func (m *RunAdhocRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunAdhocRequest.Marshal(b, m, deterministic)
}
func (m *RunAdhocRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunAdhocRequest.Merge(m, src)
}
func (m *RunAdhocRequest) XXX_Size() int {
	return xxx_messageInfo_RunAdhocRequest.Size(m)
}
func (m *RunAdhocRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunAdhocRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunAdhocRequest proto.InternalMessageInfo

func (m *RunAdhocRequest) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *RunAdhocRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *RunAdhocRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *RunAdhocRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

type RunAdhocResult struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunAdhocResult) Reset()         { *m = RunAdhocResult{} }
func (m *RunAdhocResult) String() string { return proto.CompactTextString(m) }
func (*RunAdhocResult) ProtoMessage()    {}
func (*RunAdhocResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{11}
}

func (m *RunAdhocResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunAdhocResult.Unmarshal(m, b)
}
func (m *RunAdhocResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunAdhocResult.Marshal(b, m, deterministic)
}
func (m *RunAdhocResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunAdhocResult.Merge(m, src)
}
func (m *RunAdhocResult) XXX_Size() int {
	return xxx_messageInfo_RunAdhocResult.Size(m)
}
func (m *RunAdhocResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RunAdhocResult.DiscardUnknown(m)
}

var xxx_messageInfo_RunAdhocResult proto.InternalMessageInfo

func (m *RunAdhocResult) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Success              bool     `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Finished             bool     `protobuf:"varint,6,opt,name=finished,proto3" json:"finished,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Project              string   `protobuf:"bytes,8,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{12}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Result) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Result) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Result) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type WatchStream struct {
	Stream               []byte   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchStream) Reset()         { *m = WatchStream{} }
func (m *WatchStream) String() string { return proto.CompactTextString(m) }
func (*WatchStream) ProtoMessage()    {}
func (*WatchStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{13}
}

func (m *WatchStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchStream.Unmarshal(m, b)
}
func (m *WatchStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchStream.Marshal(b, m, deterministic)
}
func (m *WatchStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchStream.Merge(m, src)
}
func (m *WatchStream) XXX_Size() int {
	return xxx_messageInfo_WatchStream.Size(m)
}
func (m *WatchStream) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchStream.DiscardUnknown(m)
}

var xxx_messageInfo_WatchStream proto.InternalMessageInfo

func (m *WatchStream) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

type WatchRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{14}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

func (m *WatchRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type GetInventoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInventoryRequest) Reset()         { *m = GetInventoryRequest{} }
func (m *GetInventoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetInventoryRequest) ProtoMessage()    {}
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{15}
}

func (m *GetInventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInventoryRequest.Unmarshal(m, b)
}
func (m *GetInventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInventoryRequest.Marshal(b, m, deterministic)
}
func (m *GetInventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventoryRequest.Merge(m, src)
}
func (m *GetInventoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetInventoryRequest.Size(m)
}
func (m *GetInventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventoryRequest proto.InternalMessageInfo

func (m *GetInventoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetInventoryResponse struct {
	Item                 *Inventory `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetInventoryResponse) Reset()         { *m = GetInventoryResponse{} }
func (m *GetInventoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetInventoryResponse) ProtoMessage()    {}
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{16}
}

func (m *GetInventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInventoryResponse.Unmarshal(m, b)
}
func (m *GetInventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInventoryResponse.Marshal(b, m, deterministic)
}
func (m *GetInventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInventoryResponse.Merge(m, src)
}
func (m *GetInventoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetInventoryResponse.Size(m)
}
func (m *GetInventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInventoryResponse proto.InternalMessageInfo

func (m *GetInventoryResponse) GetItem() *Inventory {
	if m != nil {
		return m.Item
	}
	return nil
}

type GetResultRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultRequest) Reset()         { *m = GetResultRequest{} }
func (m *GetResultRequest) String() string { return proto.CompactTextString(m) }
func (*GetResultRequest) ProtoMessage()    {}
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{17}
}

func (m *GetResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultRequest.Unmarshal(m, b)
}
func (m *GetResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultRequest.Marshal(b, m, deterministic)
}
func (m *GetResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultRequest.Merge(m, src)
}
func (m *GetResultRequest) XXX_Size() int {
	return xxx_messageInfo_GetResultRequest.Size(m)
}
func (m *GetResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultRequest proto.InternalMessageInfo

func (m *GetResultRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type GetResultResponse struct {
	Item                 *Result  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultResponse) Reset()         { *m = GetResultResponse{} }
func (m *GetResultResponse) String() string { return proto.CompactTextString(m) }
func (*GetResultResponse) ProtoMessage()    {}
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{18}
}

func (m *GetResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultResponse.Unmarshal(m, b)
}
func (m *GetResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultResponse.Marshal(b, m, deterministic)
}
func (m *GetResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultResponse.Merge(m, src)
}
func (m *GetResultResponse) XXX_Size() int {
	return xxx_messageInfo_GetResultResponse.Size(m)
}
func (m *GetResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultResponse proto.InternalMessageInfo

func (m *GetResultResponse) GetItem() *Result {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListResultRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResultRequest) Reset()         { *m = ListResultRequest{} }
func (m *ListResultRequest) String() string { return proto.CompactTextString(m) }
func (*ListResultRequest) ProtoMessage()    {}
func (*ListResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{19}
}

func (m *ListResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResultRequest.Unmarshal(m, b)
}
func (m *ListResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResultRequest.Marshal(b, m, deterministic)
}
func (m *ListResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResultRequest.Merge(m, src)
}
func (m *ListResultRequest) XXX_Size() int {
	return xxx_messageInfo_ListResultRequest.Size(m)
}
func (m *ListResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResultRequest proto.InternalMessageInfo

type ListResultResponse struct {
	Items                []*Result `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListResultResponse) Reset()         { *m = ListResultResponse{} }
func (m *ListResultResponse) String() string { return proto.CompactTextString(m) }
func (*ListResultResponse) ProtoMessage()    {}
func (*ListResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77244b2e22c40370, []int{20}
}

func (m *ListResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResultResponse.Unmarshal(m, b)
}
func (m *ListResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResultResponse.Marshal(b, m, deterministic)
}
func (m *ListResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResultResponse.Merge(m, src)
}
func (m *ListResultResponse) XXX_Size() int {
	return xxx_messageInfo_ListResultResponse.Size(m)
}
func (m *ListResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResultResponse proto.InternalMessageInfo

func (m *ListResultResponse) GetItems() []*Result {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "api.Project")
	proto.RegisterType((*Host)(nil), "api.Host")
	proto.RegisterMapType((map[string]string)(nil), "api.Host.VarsEntry")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterMapType((map[string]string)(nil), "api.Group.VarsEntry")
	proto.RegisterType((*Inventory)(nil), "api.Inventory")
	proto.RegisterType((*CreateProjectRequest)(nil), "api.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "api.CreateProjectResponse")
	proto.RegisterType((*ListProjectRequest)(nil), "api.ListProjectRequest")
	proto.RegisterType((*ListProjectResponse)(nil), "api.ListProjectResponse")
	proto.RegisterType((*RunPlaybookRequest)(nil), "api.RunPlaybookRequest")
	proto.RegisterType((*RunPlaybookResult)(nil), "api.RunPlaybookResult")
	proto.RegisterType((*RunAdhocRequest)(nil), "api.RunAdhocRequest")
	proto.RegisterType((*RunAdhocResult)(nil), "api.RunAdhocResult")
	proto.RegisterType((*Result)(nil), "api.Result")
	proto.RegisterType((*WatchStream)(nil), "api.WatchStream")
	proto.RegisterType((*WatchRequest)(nil), "api.WatchRequest")
	proto.RegisterType((*GetInventoryRequest)(nil), "api.GetInventoryRequest")
	proto.RegisterType((*GetInventoryResponse)(nil), "api.GetInventoryResponse")
	proto.RegisterType((*GetResultRequest)(nil), "api.GetResultRequest")
	proto.RegisterType((*GetResultResponse)(nil), "api.GetResultResponse")
	proto.RegisterType((*ListResultRequest)(nil), "api.ListResultRequest")
	proto.RegisterType((*ListResultResponse)(nil), "api.ListResultResponse")
}

func init() { proto.RegisterFile("kobe.proto", fileDescriptor_77244b2e22c40370) }

var fileDescriptor_77244b2e22c40370 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0x27, 0x8e, 0x77, 0x7d, 0xbc, 0x2c, 0xbb, 0x93, 0x74, 0xeb, 0x5a, 0x48, 0x0d, 0x83,
	0x0a, 0x11, 0x42, 0x2b, 0x14, 0x7e, 0xb6, 0x2d, 0x48, 0xd0, 0xa2, 0x6a, 0x5b, 0xc1, 0xc5, 0xca,
	0x20, 0xb8, 0x9e, 0xd8, 0x43, 0x63, 0x92, 0x78, 0xcc, 0xcc, 0x78, 0x21, 0x4f, 0xc0, 0x2d, 0x8f,
	0xc2, 0xa3, 0x70, 0xc1, 0x03, 0xa1, 0xf9, 0xf3, 0x4f, 0x12, 0xa9, 0x5c, 0x70, 0xe7, 0x6f, 0xce,
	0x99, 0x73, 0xbe, 0x33, 0xe7, 0x3b, 0x47, 0x06, 0x58, 0xb1, 0x05, 0xbd, 0xaa, 0x38, 0x93, 0x0c,
	0x0d, 0x49, 0x55, 0xe0, 0x2f, 0xe0, 0xf8, 0x96, 0xb3, 0x5f, 0x68, 0x26, 0x11, 0x02, 0xbf, 0x24,
	0x1b, 0x1a, 0x7b, 0x53, 0x6f, 0x16, 0xa6, 0xfa, 0x1b, 0xbd, 0x03, 0x61, 0xb5, 0x26, 0xdb, 0x05,
	0x63, 0x2b, 0x11, 0x0f, 0xa6, 0xc3, 0x59, 0x98, 0xb6, 0x07, 0xf8, 0x6f, 0x0f, 0xfc, 0x97, 0x4c,
	0x48, 0x74, 0x06, 0x83, 0xa2, 0xb2, 0x17, 0x07, 0x45, 0xd5, 0x84, 0x1a, 0x74, 0x42, 0x21, 0xf0,
	0x2b, 0xc6, 0x65, 0x3c, 0x9c, 0x7a, 0xb3, 0x51, 0xaa, 0xbf, 0xd5, 0x59, 0x2d, 0x28, 0x8f, 0x7d,
	0xe3, 0xa7, 0xbe, 0x51, 0x02, 0x27, 0x15, 0x11, 0xe2, 0x37, 0xc6, 0xf3, 0x78, 0xa4, 0xcf, 0x1b,
	0x8c, 0x3e, 0x00, 0xff, 0x8e, 0x70, 0x11, 0x07, 0xd3, 0xe1, 0x2c, 0x9a, 0x8f, 0xaf, 0x48, 0x55,
	0x5c, 0x29, 0x02, 0x57, 0x3f, 0x12, 0x2e, 0x5e, 0x94, 0x92, 0x6f, 0x53, 0xed, 0x90, 0x5c, 0x43,
	0xd8, 0x1c, 0xa1, 0x73, 0x18, 0xae, 0xe8, 0xd6, 0xd2, 0x53, 0x9f, 0x68, 0x02, 0xa3, 0x3b, 0xb2,
	0xae, 0x1d, 0x41, 0x03, 0x9e, 0x0e, 0x1e, 0x7b, 0xf8, 0x2f, 0x0f, 0x46, 0x37, 0x9c, 0xd5, 0xd5,
	0xc1, 0xe7, 0x98, 0xc0, 0x68, 0xc9, 0x84, 0x74, 0x4f, 0x61, 0x80, 0x62, 0x9c, 0x2d, 0x8b, 0x75,
	0xce, 0x69, 0x19, 0x0f, 0xb5, 0xa1, 0xc1, 0x68, 0x66, 0x19, 0xfb, 0x9a, 0xf1, 0x44, 0x33, 0xd6,
	0xf1, 0xff, 0x3f, 0xca, 0xb7, 0x10, 0xbe, 0x2a, 0xef, 0x68, 0x29, 0x19, 0xdf, 0xa2, 0x87, 0x8e,
	0xa1, 0xa7, 0x13, 0x86, 0xcd, 0x13, 0x39, 0xb2, 0x18, 0x82, 0xd7, 0x2a, 0xbf, 0xa9, 0x21, 0x9a,
	0x43, 0x4b, 0x29, 0xb5, 0x16, 0xfc, 0x1c, 0x26, 0xdf, 0x70, 0x4a, 0x24, 0xb5, 0xd2, 0x48, 0xe9,
	0xaf, 0x35, 0x15, 0x87, 0x15, 0x72, 0x09, 0x81, 0x60, 0x35, 0xcf, 0x1c, 0x31, 0x8b, 0xf0, 0x13,
	0xb8, 0xb7, 0x13, 0x43, 0x54, 0xac, 0x14, 0x14, 0x4d, 0xc1, 0x2f, 0x24, 0xdd, 0xe8, 0x20, 0xd1,
	0xfc, 0x54, 0xa7, 0x77, 0x3e, 0xda, 0x82, 0x27, 0x80, 0xbe, 0x2b, 0x84, 0xec, 0x27, 0xc7, 0x4f,
	0x60, 0xdc, 0x3b, 0xb5, 0xe1, 0x30, 0x8c, 0xd4, 0x25, 0x57, 0x70, 0x3f, 0x9e, 0x31, 0xe1, 0xdf,
	0x01, 0xa5, 0x75, 0x79, 0x6b, 0x75, 0xeb, 0xaa, 0x89, 0xe1, 0xb8, 0x32, 0x7e, 0xb6, 0x20, 0x07,
	0xb5, 0x04, 0xad, 0xb3, 0xad, 0xaa, 0xc1, 0xe8, 0x23, 0x08, 0x0b, 0xf7, 0xda, 0x5a, 0xcb, 0xd1,
	0xfc, 0x4c, 0xe7, 0x6c, 0x7a, 0x90, 0xb6, 0x0e, 0xf8, 0x31, 0x5c, 0xf4, 0x32, 0x8b, 0x7a, 0x2d,
	0xd1, 0x7b, 0x10, 0x70, 0xfd, 0x65, 0xdf, 0x20, 0xd2, 0xf7, 0x8d, 0x31, 0xb5, 0x26, 0xfc, 0x87,
	0x07, 0x6f, 0xa7, 0x75, 0xf9, 0x2c, 0x5f, 0xb2, 0xcc, 0x31, 0xee, 0xe5, 0xf6, 0xde, 0x90, 0x5b,
	0xd7, 0x47, 0xa4, 0xa4, 0xbc, 0xb4, 0x45, 0x38, 0xa8, 0x7a, 0xb6, 0x61, 0x79, 0xbd, 0xa6, 0xba,
	0x80, 0x30, 0xb5, 0x48, 0x69, 0xac, 0x22, 0x9c, 0x6c, 0xec, 0x3c, 0x1a, 0x80, 0x3f, 0x83, 0xb3,
	0x96, 0xc8, 0x7f, 0x2f, 0xe0, 0x1f, 0x0f, 0x02, 0xeb, 0xaf, 0xd6, 0x43, 0xde, 0xac, 0x87, 0x5c,
	0x6d, 0x15, 0x21, 0x09, 0x97, 0x3f, 0x14, 0xcd, 0x8e, 0x68, 0x0f, 0x14, 0x6f, 0x5a, 0xe6, 0xda,
	0x66, 0xe8, 0x39, 0xa8, 0x2c, 0x1b, 0x2a, 0x04, 0x79, 0x4d, 0x2d, 0x43, 0x07, 0x95, 0x45, 0xd4,
	0x59, 0x46, 0x85, 0xd0, 0x3b, 0xe3, 0x24, 0x75, 0x50, 0xf5, 0xf2, 0xe7, 0xa2, 0x2c, 0xc4, 0x92,
	0xe6, 0x71, 0xa0, 0x4d, 0x0d, 0x56, 0xb7, 0x32, 0x56, 0x4a, 0x5a, 0xca, 0xf8, 0xd8, 0xc4, 0xb3,
	0xb0, 0xab, 0x8d, 0x93, 0x9e, 0x36, 0xf0, 0x23, 0x88, 0x7e, 0x22, 0x32, 0x5b, 0x7e, 0x2f, 0x39,
	0x25, 0x1b, 0x2d, 0x7f, 0xfd, 0xa5, 0xcb, 0x3b, 0x4d, 0x2d, 0xc2, 0xef, 0xc3, 0xa9, 0x76, 0x73,
	0xad, 0xbb, 0x84, 0x40, 0x12, 0xb1, 0x7a, 0xe5, 0x9e, 0xc1, 0x22, 0xfc, 0x08, 0xc6, 0x37, 0x54,
	0xb6, 0xfd, 0xb3, 0xee, 0x3b, 0x2f, 0x86, 0x9f, 0xc2, 0xa4, 0xef, 0xd6, 0xa8, 0xbf, 0x3b, 0x4c,
	0xbb, 0x62, 0x30, 0xe3, 0xf4, 0x21, 0x9c, 0xdf, 0x50, 0x69, 0xbb, 0xf3, 0x06, 0x3a, 0x9f, 0xc2,
	0x45, 0xc7, 0xd7, 0x26, 0x79, 0xd8, 0x4b, 0xd2, 0x6b, 0xb6, 0xc9, 0x30, 0x86, 0x0b, 0x35, 0x9a,
	0xbd, 0x14, 0xf8, 0xda, 0x4c, 0xf1, 0x4e, 0xac, 0x77, 0xfb, 0xe3, 0xda, 0x0b, 0x66, 0x2c, 0xf3,
	0x3f, 0x7d, 0x38, 0xfe, 0x96, 0x2d, 0xe8, 0xb3, 0xaa, 0x40, 0x2f, 0xe1, 0xad, 0xde, 0x16, 0x41,
	0x0f, 0xf4, 0x85, 0x43, 0xdb, 0x29, 0x49, 0x0e, 0x99, 0x4c, 0x5a, 0x7c, 0x84, 0x9e, 0x43, 0xd4,
	0x59, 0x1f, 0xe8, 0xbe, 0x76, 0xde, 0x5f, 0x33, 0x49, 0xbc, 0x6f, 0x68, 0x62, 0xbc, 0x80, 0xd3,
	0x6e, 0x17, 0x90, 0xf1, 0x3d, 0xd0, 0xbf, 0xe4, 0xc1, 0x01, 0x4b, 0x13, 0xe6, 0x6b, 0x88, 0x3a,
	0x4b, 0xc1, 0x52, 0xd9, 0x5f, 0x50, 0xc9, 0xe5, 0xbe, 0x41, 0x4f, 0xd6, 0x11, 0xba, 0x86, 0x13,
	0x37, 0x92, 0x68, 0xe2, 0xbc, 0xba, 0xab, 0x22, 0x19, 0xef, 0x9c, 0xda, 0x8b, 0x9f, 0x5b, 0xf5,
	0xda, 0xc1, 0xbc, 0xd0, 0x5e, 0x5d, 0xa1, 0x26, 0xe7, 0xed, 0x91, 0x91, 0x38, 0x3e, 0xfa, 0xd8,
	0x43, 0x5f, 0x42, 0xd8, 0xe8, 0x02, 0xdd, 0x73, 0xc5, 0xf5, 0x1a, 0x6e, 0xe9, 0xee, 0xc9, 0x07,
	0x1f, 0xa1, 0xaf, 0x00, 0x5a, 0x29, 0xa0, 0xcb, 0xe6, 0x85, 0xfb, 0xf7, 0xef, 0xef, 0x9d, 0xbb,
	0x00, 0x8b, 0x40, 0xff, 0xb1, 0x7c, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x62, 0x1a,
	0x92, 0xbf, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KobeApiClient is the client API for KobeApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KobeApiClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	ListProject(ctx context.Context, in *ListProjectRequest, opts ...grpc.CallOption) (*ListProjectResponse, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	RunPlaybook(ctx context.Context, in *RunPlaybookRequest, opts ...grpc.CallOption) (*RunPlaybookResult, error)
	RunAdhoc(ctx context.Context, in *RunAdhocRequest, opts ...grpc.CallOption) (*RunAdhocResult, error)
	WatchResult(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (KobeApi_WatchResultClient, error)
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	ListResult(ctx context.Context, in *ListResultRequest, opts ...grpc.CallOption) (*ListResultResponse, error)
}

type kobeApiClient struct {
	cc *grpc.ClientConn
}

func NewKobeApiClient(cc *grpc.ClientConn) KobeApiClient {
	return &kobeApiClient{cc}
}

func (c *kobeApiClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) ListProject(ctx context.Context, in *ListProjectRequest, opts ...grpc.CallOption) (*ListProjectResponse, error) {
	out := new(ListProjectResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/ListProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	out := new(GetInventoryResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/GetInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) RunPlaybook(ctx context.Context, in *RunPlaybookRequest, opts ...grpc.CallOption) (*RunPlaybookResult, error) {
	out := new(RunPlaybookResult)
	err := c.cc.Invoke(ctx, "/api.KobeApi/RunPlaybook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) RunAdhoc(ctx context.Context, in *RunAdhocRequest, opts ...grpc.CallOption) (*RunAdhocResult, error) {
	out := new(RunAdhocResult)
	err := c.cc.Invoke(ctx, "/api.KobeApi/RunAdhoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) WatchResult(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (KobeApi_WatchResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KobeApi_serviceDesc.Streams[0], "/api.KobeApi/WatchResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &kobeApiWatchResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KobeApi_WatchResultClient interface {
	Recv() (*WatchStream, error)
	grpc.ClientStream
}

type kobeApiWatchResultClient struct {
	grpc.ClientStream
}

func (x *kobeApiWatchResultClient) Recv() (*WatchStream, error) {
	m := new(WatchStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kobeApiClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/GetResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kobeApiClient) ListResult(ctx context.Context, in *ListResultRequest, opts ...grpc.CallOption) (*ListResultResponse, error) {
	out := new(ListResultResponse)
	err := c.cc.Invoke(ctx, "/api.KobeApi/ListResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KobeApiServer is the server API for KobeApi service.
type KobeApiServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	ListProject(context.Context, *ListProjectRequest) (*ListProjectResponse, error)
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	RunPlaybook(context.Context, *RunPlaybookRequest) (*RunPlaybookResult, error)
	RunAdhoc(context.Context, *RunAdhocRequest) (*RunAdhocResult, error)
	WatchResult(*WatchRequest, KobeApi_WatchResultServer) error
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	ListResult(context.Context, *ListResultRequest) (*ListResultResponse, error)
}

// UnimplementedKobeApiServer can be embedded to have forward compatible implementations.
type UnimplementedKobeApiServer struct {
}

func (*UnimplementedKobeApiServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedKobeApiServer) ListProject(ctx context.Context, req *ListProjectRequest) (*ListProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProject not implemented")
}
func (*UnimplementedKobeApiServer) GetInventory(ctx context.Context, req *GetInventoryRequest) (*GetInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (*UnimplementedKobeApiServer) RunPlaybook(ctx context.Context, req *RunPlaybookRequest) (*RunPlaybookResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunPlaybook not implemented")
}
func (*UnimplementedKobeApiServer) RunAdhoc(ctx context.Context, req *RunAdhocRequest) (*RunAdhocResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAdhoc not implemented")
}
func (*UnimplementedKobeApiServer) WatchResult(req *WatchRequest, srv KobeApi_WatchResultServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchResult not implemented")
}
func (*UnimplementedKobeApiServer) GetResult(ctx context.Context, req *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}
func (*UnimplementedKobeApiServer) ListResult(ctx context.Context, req *ListResultRequest) (*ListResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResult not implemented")
}

func RegisterKobeApiServer(s *grpc.Server, srv KobeApiServer) {
	s.RegisterService(&_KobeApi_serviceDesc, srv)
}

func _KobeApi_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_ListProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).ListProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/ListProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).ListProject(ctx, req.(*ListProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/GetInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_RunPlaybook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunPlaybookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).RunPlaybook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/RunPlaybook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).RunPlaybook(ctx, req.(*RunPlaybookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_RunAdhoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAdhocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).RunAdhoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/RunAdhoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).RunAdhoc(ctx, req.(*RunAdhocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_WatchResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KobeApiServer).WatchResult(m, &kobeApiWatchResultServer{stream})
}

type KobeApi_WatchResultServer interface {
	Send(*WatchStream) error
	grpc.ServerStream
}

type kobeApiWatchResultServer struct {
	grpc.ServerStream
}

func (x *kobeApiWatchResultServer) Send(m *WatchStream) error {
	return x.ServerStream.SendMsg(m)
}

func _KobeApi_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/GetResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KobeApi_ListResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KobeApiServer).ListResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.KobeApi/ListResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KobeApiServer).ListResult(ctx, req.(*ListResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KobeApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.KobeApi",
	HandlerType: (*KobeApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _KobeApi_CreateProject_Handler,
		},
		{
			MethodName: "ListProject",
			Handler:    _KobeApi_ListProject_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _KobeApi_GetInventory_Handler,
		},
		{
			MethodName: "RunPlaybook",
			Handler:    _KobeApi_RunPlaybook_Handler,
		},
		{
			MethodName: "RunAdhoc",
			Handler:    _KobeApi_RunAdhoc_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _KobeApi_GetResult_Handler,
		},
		{
			MethodName: "ListResult",
			Handler:    _KobeApi_ListResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchResult",
			Handler:       _KobeApi_WatchResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kobe.proto",
}
